receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

extensions:
  health_check: {}

exporters:
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
  clickhouse:
    endpoint: tcp://clickhouse:9000?dial_timeout=10s
    database: otel
    async_insert: true
    ttl: 72h
    create_schema: true
    logs_table_name: otel_logs
    traces_table_name: otel_traces
    metrics_table_name: otel_metrics
    timeout: 5s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

processors:
  batch:
    timeout: 5s
    send_batch_size: 100000
  transform:
    error_mode: ignore
    trace_statements:
      - context: span
        statements:
          - set(status.code, STATUS_CODE_OK) where attributes["http.status_code"] == 200

connectors:
  spanmetrics:
    histogram:
      explicit:
        buckets: [100us, 1ms, 2ms, 6ms, 10ms, 100ms, 250ms]

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [transform]
      exporters:
        - clickhouse
        #- otlp
        - spanmetrics
    metrics:
      receivers: [otlp, spanmetrics]
      exporters: [clickhouse]
    logs:
      receivers: [otlp]
      exporters: [clickhouse]
