---
security:
  readonly: false
  cookie:
    same_site: lax
    secure: false
  enable_auth: false
  authorization:
    check_latest_update_interval: 30s
  authentication:
    access_token_ttl: 15m
    refresh_token_ttl: 1d
    disable_sign_up: false
    providers:
      enable_native: false
database:
  file:
    folder: "/perses"
    extension: json
    case_sensitive: false
dashboard: {}
provisioning:
  folders:
    - /etc/perses/provisioning
  interval: 1h
datasource:
  global:
    disable: false
  project:
    disable: false
  disable_local: false
variable:
  global:
    disable: false
  project:
    disable: false
  disable_local: false
ephemeral_dashboard:
  enable: false
  cleanup_interval: 0s
frontend:
  disable: false
  explorer:
    enable: false
  time_range:
    disable_custom: false
    options:
      - 5m
      - 15m
      - 30m
      - 1h
      - 6h
      - 12h
      - 1d
      - 1w
      - 2w
plugin:
  path: "/etc/perses/plugins"
  archive_path: "/etc/perses/plugins-archive"
