name: e2e
on:
  pull_request: {}

jobs:
  e2e:
    name: e2e
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: "operator/go.mod"
      - run: make test-e2e
        working-directory: operator
