name: test
on:
  pull_request: {}

jobs:
  test:
    name: test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: "operator/go.mod"
      - run: make test
        working-directory: operator
